version: '3.6'

services:
  cron:
    build: ./cron
    restart: unless-stopped
    network_mode: "host"
    container_name: cron
    volumes:
      - ./cron/MemTester:/app/
      - public:/app/public
    working_dir: /app
    environment:
      API_HOST: 'http://memtest.dev.btech'

  web:
    build: ./web
    restart: unless-stopped
    container_name: web
    ports:
      - 3333:3333
    volumes:
      - public:/app/build/public/public

  react:
    build:
      context: ./frontend
    restart: unless-stopped
    container_name: react
    ports:
      - 8080:80
    environment:
      API_HOST: 'web'

  mariadb:
    image: mariadb
    restart: unless-stopped
    container_name: mariadb
    ports:
      - 3306:3306
    volumes:
      - /apps/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=ldap2retro
      - MYSQL_PASSWORD=ldap2retro
      - MYSQL_USER=memtest
      - MYSQL_DATABASE=memtest
      - TZ=Europe/Oslo
    command:
      [
        'mysqld',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci',
        '--default-time-zone=+02:00'
      ]

volumes:
  public:
networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.16.0.0/24"
          gateway: "172.16.0.1"
