version: '3.6'

services:
  cron:
    build: ./cron
    network_mode: "host"
    container_name: cron
    volumes:
      - ./cron/MemTester:/app/
    working_dir: /app
    environment:
      API_HOST: 'http://localhost:333'

  web:
    build: ./web
    container_name: web
    ports:
      - 3333:3333

  mariadb:
    image: mariadb
    container_name: mariadb
    restart: unless-stopped
    ports:
      - 3306:3306
    volumes:
      - /apps/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=ldap2retro
      - MYSQL_PASSWORD=ldap2retro
      - MYSQL_USER=memtest
      - MYSQL_DATABASE=memtest
      - TZ=Europe/Oslo
    command:
      [
        'mysqld',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci',
        '--default-time-zone=+02:00'
      ]
