version: '3.6'

services:
  cron:
    build: ./cron
    network_mode: "host"
    container_name: cron
    volumes:
      - ./cron/MemTester:/app/
    working_dir: /app
    environment:
      - PRODUCTION='true'
  web:
    build: ./web
    container_name: web
    ports:
      - 3333:3333
