version: '3.6'

services:
  cron:
    build: ./cron
    network_mode: "host"
    container_name: cron
    volumes:
      - ./cron/MemTester:/app/
    working_dir: /app
    environment:
      - PRODUCTION='true'
  web:
    build: ./web
    container_name: web
    ports:
      - 3333:3333
  mariadb:
    image: mariadb
    restart: on-failure
    ports:
      - 3306:3306
    volumes:
      - ${PWD}/mariadb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ldap2retro
      MYSQL_DATABASE: memtest
      MYSQL_USER: memtest
      MYSQL_PASSWORD: ldap2retro
